//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funnel_Field
    {
        public Funnel_Field()
        {
            this.ModelReviews = new HashSet<ModelReview>();
        }
    
        public int FunnelFieldId { get; set; }
        public int FunnelId { get; set; }
        public int FieldId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    
        public virtual Field Field { get; set; }
        public virtual Funnel Funnel { get; set; }
        public virtual ICollection<ModelReview> ModelReviews { get; set; }
    }
}
