//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImprovementTacticStageTransitionMap
    {
        public int ImprovementTacticStageTransitionMapId { get; set; }
        public int ImprovementTacticID { get; set; }
        public int Weight { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    
        public virtual Plan_Improvement_Campaign_Program_Tactic Plan_Improvement_Campaign_Program_Tactic { get; set; }
    }
}
