//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegrationTypeAttribute
    {
        public IntegrationTypeAttribute()
        {
            this.IntegrationInstance_Attribute = new HashSet<IntegrationInstance_Attribute>();
        }
    
        public int IntegrationTypeAttributeId { get; set; }
        public int IntegrationTypeId { get; set; }
        public string Attribute { get; set; }
        public string AttributeType { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<IntegrationInstance_Attribute> IntegrationInstance_Attribute { get; set; }
    }
}
