//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model_Audience_Event
    {
        public int ModelAudienceEventId { get; set; }
        public int ModelId { get; set; }
        public string Quarter { get; set; }
        public Nullable<long> NumberofContacts { get; set; }
        public Nullable<double> ContactToInquiryConversion { get; set; }
        public Nullable<double> EventsBudget { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    
        public virtual Model Model { get; set; }
    }
}
