//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan_Improvement_Campaign_Program_Tactic
    {
        public Plan_Improvement_Campaign_Program_Tactic()
        {
            this.ImprovementTacticStageTransitionMaps = new HashSet<ImprovementTacticStageTransitionMap>();
        }
    
        public int ImprovementPlanTacticId { get; set; }
        public int ImprovementPlanProgramId { get; set; }
        public int ImprovementTacticTypeId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> VerticalId { get; set; }
        public Nullable<int> AudienceId { get; set; }
        public Nullable<System.Guid> GeographyId { get; set; }
        public System.Guid BusinessUnitId { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public double Cost { get; set; }
        public Nullable<double> CostActual { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual BusinessUnit BusinessUnit { get; set; }
        public virtual Geography Geography { get; set; }
        public virtual ICollection<ImprovementTacticStageTransitionMap> ImprovementTacticStageTransitionMaps { get; set; }
        public virtual ImprovementTacticType ImprovementTacticType { get; set; }
        public virtual ImprovementTacticType ImprovementTacticType1 { get; set; }
        public virtual Plan_Improvement_Campaign_Program Plan_Improvement_Campaign_Program { get; set; }
        public virtual Plan_Improvement_Campaign_Program_Tactic Plan_Improvement_Campaign_Program_Tactic1 { get; set; }
        public virtual Plan_Improvement_Campaign_Program_Tactic Plan_Improvement_Campaign_Program_Tactic2 { get; set; }
        public virtual Vertical Vertical { get; set; }
    }
}
