-- Use MRP DB

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_NAME = 'ImprovementTacticType')
BEGIN
	IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_NAME = 'ImprovementTacticType' AND COLUMN_NAME = 'ModifiedDate')
	BEGIN
		ALTER TABLE ImprovementTacticType ADD ModifiedDate DATETIME NULL
	END

	IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_NAME = 'ImprovementTacticType' AND COLUMN_NAME = 'ModifiedBy')
	BEGIN
		ALTER TABLE ImprovementTacticType ADD ModifiedBy uniqueidentifier NULL
	END
END
