//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDSService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Activity
    {
        public int ClientActivityId { get; set; }
        public System.Guid ClientId { get; set; }
        public int ApplicationActivityId { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Application_Activity Application_Activity { get; set; }
        public virtual Client Client { get; set; }
    }
}
