//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDSService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientDatabase
    {
        public ClientDatabase()
        {
            this.UserClientDatabases = new HashSet<UserClientDatabase>();
        }
    
        public int Id { get; set; }
        public System.Guid ClientID { get; set; }
        public string DatabaseName { get; set; }
        public byte[] EncryptedConnectionString { get; set; }
    
        public virtual ICollection<UserClientDatabase> UserClientDatabases { get; set; }
        public virtual Client Client { get; set; }
    }
}
