//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDSService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomRestriction
    {
        public int CustomRestrictionId { get; set; }
        public System.Guid UserId { get; set; }
        public string CustomField { get; set; }
        public string CustomFieldId { get; set; }
        public short Permission { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.Guid> ApplicationId { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
