//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDSService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_Application
    {
        public Menu_Application()
        {
            this.Menu_Application1 = new HashSet<Menu_Application>();
            this.Role_Permission = new HashSet<Role_Permission>();
        }
    
        public int MenuApplicationId { get; set; }
        public Nullable<int> ParentApplicationId { get; set; }
        public System.Guid ApplicationId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsDisplayInMenu { get; set; }
        public int SortOrder { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual ICollection<Menu_Application> Menu_Application1 { get; set; }
        public virtual Menu_Application Menu_Application2 { get; set; }
        public virtual ICollection<Role_Permission> Role_Permission { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
