//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDSService
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.CustomRestrictions = new HashSet<CustomRestriction>();
            this.CustomRestrictions1 = new HashSet<CustomRestriction>();
            this.PasswordResetRequests = new HashSet<PasswordResetRequest>();
            this.Role_Activity_Permission = new HashSet<Role_Activity_Permission>();
            this.User_Activity_Permission = new HashSet<User_Activity_Permission>();
            this.User_Activity_Permission1 = new HashSet<User_Activity_Permission>();
            this.User_Application = new HashSet<User_Application>();
            this.User1 = new HashSet<User>();
            this.Applications = new HashSet<Application>();
            this.Applications1 = new HashSet<Application>();
            this.Application_Role = new HashSet<Application_Role>();
            this.Application_Role1 = new HashSet<Application_Role>();
            this.Clients = new HashSet<Client>();
            this.Clients1 = new HashSet<Client>();
            this.Menu_Application = new HashSet<Menu_Application>();
            this.Menu_Application1 = new HashSet<Menu_Application>();
            this.Roles = new HashSet<Role>();
            this.Roles1 = new HashSet<Role>();
            this.Role_Permission = new HashSet<Role_Permission>();
            this.Role_Permission1 = new HashSet<Role_Permission>();
            this.User_Application1 = new HashSet<User_Application>();
            this.User_Application2 = new HashSet<User_Application>();
            this.UserClientDatabases = new HashSet<UserClientDatabase>();
        }
    
        public System.Guid UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public System.Guid ClientId { get; set; }
        public byte[] ProfilePhoto { get; set; }
        public string DisplayName { get; set; }
        public string JobTitle { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> SecurityQuestionId { get; set; }
        public string Answer { get; set; }
        public string Phone { get; set; }
        public Nullable<System.Guid> ManagerId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<CustomRestriction> CustomRestrictions { get; set; }
        public virtual ICollection<CustomRestriction> CustomRestrictions1 { get; set; }
        public virtual ICollection<PasswordResetRequest> PasswordResetRequests { get; set; }
        public virtual ICollection<Role_Activity_Permission> Role_Activity_Permission { get; set; }
        public virtual SecurityQuestion SecurityQuestion { get; set; }
        public virtual ICollection<User_Activity_Permission> User_Activity_Permission { get; set; }
        public virtual ICollection<User_Activity_Permission> User_Activity_Permission1 { get; set; }
        public virtual ICollection<User_Application> User_Application { get; set; }
        public virtual ICollection<User> User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual ICollection<Application> Applications { get; set; }
        public virtual ICollection<Application> Applications1 { get; set; }
        public virtual ICollection<Application_Role> Application_Role { get; set; }
        public virtual ICollection<Application_Role> Application_Role1 { get; set; }
        public virtual ICollection<Client> Clients { get; set; }
        public virtual ICollection<Client> Clients1 { get; set; }
        public virtual ICollection<Menu_Application> Menu_Application { get; set; }
        public virtual ICollection<Menu_Application> Menu_Application1 { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<Role> Roles1 { get; set; }
        public virtual ICollection<Role_Permission> Role_Permission { get; set; }
        public virtual ICollection<Role_Permission> Role_Permission1 { get; set; }
        public virtual ICollection<User_Application> User_Application1 { get; set; }
        public virtual ICollection<User_Application> User_Application2 { get; set; }
        public virtual ICollection<UserClientDatabase> UserClientDatabases { get; set; }
    }
}
