//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDSService
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserClientDatabase
    {
        public int Id { get; set; }
        public int ClientDatabaseID { get; set; }
        public System.Guid UserID { get; set; }
    
        public virtual ClientDatabase ClientDatabase { get; set; }
    }
}
