/* To be executed in Gameplan database */

ALTER TABLE Model ALTER COLUMN AddressableContacts BIGINT NOT NULL
ALTER TABLE Model_Audience_Event ALTER COLUMN NumberofContacts BIGINT NULL
ALTER TABLE Model_Funnel ALTER COLUMN ExpectedLeadCount BIGINT NOT NULL
ALTER TABLE [Plan] ALTER COLUMN MQLs FLOAT NOT NULL
ALTER TABLE Plan_Campaign ALTER COLUMN INQs BIGINT NULL
ALTER TABLE Plan_Campaign ALTER COLUMN MQLs FLOAT NULL
ALTER TABLE Plan_Campaign_Program ALTER COLUMN INQs BIGINT NULL
ALTER TABLE Plan_Campaign_Program ALTER COLUMN MQLs FLOAT NULL
ALTER TABLE Plan_Campaign_Program_Tactic ALTER COLUMN INQs BIGINT NOT NULL
ALTER TABLE Plan_Campaign_Program_Tactic ALTER COLUMN INQsActual BIGINT NULL
ALTER TABLE Plan_Campaign_Program_Tactic ALTER COLUMN MQLs FLOAT NOT NULL
ALTER TABLE Plan_Campaign_Program_Tactic ALTER COLUMN MQLsActual FLOAT NULL
ALTER TABLE Plan_Campaign_Program_Tactic ALTER COLUMN CWs FLOAT NULL
ALTER TABLE Plan_Campaign_Program_Tactic ALTER COLUMN CWsActual FLOAT NULL
ALTER TABLE Plan_Campaign_Program_Tactic_Actual ALTER COLUMN Actualvalue FLOAT NOT NULL
--ALTER TABLE Plan_Improvement_Campaign_Program_Tactic_Actual ALTER COLUMN Actualvalue FLOAT NOT NULL
ALTER TABLE TacticType ALTER COLUMN ProjectedInquiries BIGINT NULL
ALTER TABLE TacticType ALTER COLUMN ProjectedMQLs FLOAT NULL
ALTER TABLE TacticType ALTER COLUMN ProjectedRevenue FLOAT NULL
