//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alert_Rules
    {
        public Alert_Rules()
        {
            this.Alerts = new HashSet<Alert>();
        }
    
        public int RuleId { get; set; }
        public string RuleSummary { get; set; }
        public int EntityId { get; set; }
        public string EntityType { get; set; }
        public string Indicator { get; set; }
        public string IndicatorComparision { get; set; }
        public int IndicatorGoal { get; set; }
        public int CompletionGoal { get; set; }
        public string Frequency { get; set; }
        public Nullable<byte> DayOfWeek { get; set; }
        public Nullable<byte> DateOfMonth { get; set; }
        public Nullable<System.DateTime> LastProcessingDate { get; set; }
        public Nullable<System.DateTime> NextProcessingDate { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid ClientId { get; set; }
        public bool IsDisabled { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    
        public virtual ICollection<Alert> Alerts { get; set; }
    }
}
