//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttrPositionConfig
    {
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public double XValue { get; set; }
        public double YValue { get; set; }
        public Nullable<int> DimensionId { get; set; }
        public string DimensionValue { get; set; }
        public Nullable<double> Weight { get; set; }
    
        public virtual Dimension Dimension { get; set; }
    }
}
