//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget
    {
        public Budget()
        {
            this.Budget_Detail = new HashSet<Budget_Detail>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Desc { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public bool IsOther { get; set; }
        public int ClientId { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual Budget Budget1 { get; set; }
        public virtual Budget Budget2 { get; set; }
        public virtual ICollection<Budget_Detail> Budget_Detail { get; set; }
    }
}
