//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget_DetailAmount
    {
        public int Id { get; set; }
        public int BudgetDetailId { get; set; }
        public string Period { get; set; }
        public Nullable<double> Budget { get; set; }
        public Nullable<double> Forecast { get; set; }
    
        public virtual Budget_Detail Budget_Detail { get; set; }
    }
}
