//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget_Columns
    {
        public int Id { get; set; }
        public int Column_SetId { get; set; }
        public int CustomFieldId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<bool> IsTimeFrame { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string MapTableName { get; set; }
        public Nullable<int> ValueOnEditable { get; set; }
        public string ValidationType { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual Budget_ColumnSet Budget_ColumnSet { get; set; }
        public virtual CustomField CustomField { get; set; }
    }
}
