//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignNameConvention
    {
        public int CampaignNameConventionId { get; set; }
        public string TableName { get; set; }
        public string FieldName { get; set; }
        public Nullable<int> CustomFieldId { get; set; }
        public int Sequence { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> CustomNameCharNo { get; set; }
        public int ClientId { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual CustomField CustomField { get; set; }
    }
}
