//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeLog
    {
        public int ChangeLogId { get; set; }
        public string TableName { get; set; }
        public Nullable<int> ObjectId { get; set; }
        public Nullable<int> ParentObjectId { get; set; }
        public Nullable<int> ComponentId { get; set; }
        public string ComponentTitle { get; set; }
        public string ComponentType { get; set; }
        public string ActionName { get; set; }
        public string ActionSuffix { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public bool IsDeleted { get; set; }
        public int ClientId { get; set; }
        public int UserId { get; set; }
    }
}
