//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigurationTestCas
    {
        public int id { get; set; }
        public string TestCaseName { get; set; }
        public string TestCaseQuery { get; set; }
        public string TestStoredProcedure { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool isDeleted { get; set; }
    }
}
