//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomRestriction
    {
        public int CustomRestrictionId { get; set; }
        public int CustomFieldId { get; set; }
        public int CustomFieldOptionId { get; set; }
        public short Permission { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UserId { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual CustomField CustomField { get; set; }
        public virtual CustomFieldOption CustomFieldOption { get; set; }
    }
}
