//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomFieldDependency_Temp
    {
        public Nullable<int> ParentCustomFieldId { get; set; }
        public int ParentOptionId { get; set; }
        public int ChildCustomFieldId { get; set; }
        public Nullable<int> ChildOptionId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public int DependencyId { get; set; }
        public int CreatedBy { get; set; }
    }
}
