//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomField_Entity
    {
        public int CustomFieldEntityId { get; set; }
        public int EntityId { get; set; }
        public int CustomFieldId { get; set; }
        public string Value { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<byte> Weightage { get; set; }
        public Nullable<byte> CostWeightage { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual CustomField CustomField { get; set; }
    }
}
