//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomField_Entity_StageWeight
    {
        public long StageWeightId { get; set; }
        public int CustomFieldEntityId { get; set; }
        public string StageTitle { get; set; }
        public byte Weightage { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
    
        public virtual CustomField_Entity CustomField_Entity { get; set; }
    }
}
