//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dashboard
    {
        public Dashboard()
        {
            this.Dashboard1 = new HashSet<Dashboard>();
            this.DashboardDimensions = new HashSet<DashboardDimension>();
            this.DashboardPages = new HashSet<DashboardPage>();
            this.DrillDataConfigs = new HashSet<DrillDataConfig>();
            this.HomepageContents = new HashSet<HomepageContent>();
            this.KeyDatas = new HashSet<KeyData>();
            this.MenuItems = new HashSet<MenuItem>();
            this.ReportTables = new HashSet<ReportTable>();
            this.Role_Permission = new HashSet<Role_Permission>();
            this.User_Permission = new HashSet<User_Permission>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public int DisplayOrder { get; set; }
        public string CustomCSS { get; set; }
        public Nullable<int> Rows { get; set; }
        public Nullable<int> Columns { get; set; }
        public Nullable<int> ParentDashboardId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsComparisonDisplay { get; set; }
        public Nullable<int> HelpTextId { get; set; }
    
        public virtual ICollection<Dashboard> Dashboard1 { get; set; }
        public virtual Dashboard Dashboard2 { get; set; }
        public virtual HelpText HelpText { get; set; }
        public virtual ICollection<DashboardDimension> DashboardDimensions { get; set; }
        public virtual ICollection<DashboardPage> DashboardPages { get; set; }
        public virtual ICollection<DrillDataConfig> DrillDataConfigs { get; set; }
        public virtual ICollection<HomepageContent> HomepageContents { get; set; }
        public virtual ICollection<KeyData> KeyDatas { get; set; }
        public virtual ICollection<MenuItem> MenuItems { get; set; }
        public virtual ICollection<ReportTable> ReportTables { get; set; }
        public virtual ICollection<Role_Permission> Role_Permission { get; set; }
        public virtual ICollection<User_Permission> User_Permission { get; set; }
    }
}
