//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardDimension
    {
        public DashboardDimension()
        {
            this.HomepageDimensions = new HashSet<HomepageDimension>();
        }
    
        public int id { get; set; }
        public int DashboardId { get; set; }
        public int DimensionId { get; set; }
        public string DimensionType { get; set; }
        public double DisplayOrder { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DashboardPageID { get; set; }
    
        public virtual Dashboard Dashboard { get; set; }
        public virtual Dimension Dimension { get; set; }
        public virtual ICollection<HomepageDimension> HomepageDimensions { get; set; }
    }
}
