//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardContent
    {
        public DashboardContent()
        {
            this.DrillDataConfigs = new HashSet<DrillDataConfig>();
        }
    
        public int id { get; set; }
        public string DisplayName { get; set; }
        public int DashboardId { get; set; }
        public double DisplayOrder { get; set; }
        public Nullable<int> ReportTableId { get; set; }
        public Nullable<int> ReportGraphId { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Width { get; set; }
        public string Position { get; set; }
        public Nullable<bool> IsCumulativeData { get; set; }
        public Nullable<bool> IsCommunicativeData { get; set; }
        public Nullable<int> DashboardPageID { get; set; }
        public bool IsDeleted { get; set; }
        public string DisplayIfZero { get; set; }
        public Nullable<int> KeyDataId { get; set; }
        public Nullable<int> HelpTextId { get; set; }
    
        public virtual HelpText HelpText { get; set; }
        public virtual KeyData KeyData { get; set; }
        public virtual ICollection<DrillDataConfig> DrillDataConfigs { get; set; }
    }
}
