//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dimension_RestrictedDimensionValues
    {
        public int Id { get; set; }
        public int DimensionId { get; set; }
        public string DimensionValue { get; set; }
        public int RestrictedDimentionId { get; set; }
        public string RestrictedDimensionValue { get; set; }
    
        public virtual Dimension Dimension { get; set; }
        public virtual Dimension Dimension1 { get; set; }
    }
}
