//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dimension
    {
        public Dimension()
        {
            this.DashboardDimensions = new HashSet<DashboardDimension>();
            this.AttrPositionConfigs = new HashSet<AttrPositionConfig>();
            this.Dimension_RestrictedDimensionValues = new HashSet<Dimension_RestrictedDimensionValues>();
            this.Dimension_RestrictedDimensionValues1 = new HashSet<Dimension_RestrictedDimensionValues>();
            this.GoalDimensions = new HashSet<GoalDimension>();
            this.KeyDataDimensions = new HashSet<KeyDataDimension>();
            this.ReportAxis = new HashSet<ReportAxi>();
            this.ReportTableColumns = new HashSet<ReportTableColumn>();
            this.ReportTableDimensions = new HashSet<ReportTableDimension>();
            this.Role_RestrictedDimensionValues = new HashSet<Role_RestrictedDimensionValues>();
            this.User_RestrictedDimensionValues = new HashSet<User_RestrictedDimensionValues>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string TableName { get; set; }
        public string ColumnName { get; set; }
        public string Formula { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsDateDimension { get; set; }
        public string ValueFormula { get; set; }
        public Nullable<bool> ComputeAllValues { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual ICollection<DashboardDimension> DashboardDimensions { get; set; }
        public virtual ICollection<AttrPositionConfig> AttrPositionConfigs { get; set; }
        public virtual ICollection<Dimension_RestrictedDimensionValues> Dimension_RestrictedDimensionValues { get; set; }
        public virtual ICollection<Dimension_RestrictedDimensionValues> Dimension_RestrictedDimensionValues1 { get; set; }
        public virtual ICollection<GoalDimension> GoalDimensions { get; set; }
        public virtual ICollection<KeyDataDimension> KeyDataDimensions { get; set; }
        public virtual ICollection<ReportAxi> ReportAxis { get; set; }
        public virtual ICollection<ReportTableColumn> ReportTableColumns { get; set; }
        public virtual ICollection<ReportTableDimension> ReportTableDimensions { get; set; }
        public virtual ICollection<Role_RestrictedDimensionValues> Role_RestrictedDimensionValues { get; set; }
        public virtual ICollection<User_RestrictedDimensionValues> User_RestrictedDimensionValues { get; set; }
    }
}
