//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrillDataConfig
    {
        public int Id { get; set; }
        public int DashboardId { get; set; }
        public string DisplayByText { get; set; }
        public string DisplayByQuery { get; set; }
        public string PrimaryColumns { get; set; }
        public Nullable<bool> DisplayMeasureValue { get; set; }
        public Nullable<int> DashboardContentId { get; set; }
    
        public virtual Dashboard Dashboard { get; set; }
        public virtual DashboardContent DashboardContent { get; set; }
    }
}
