//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityIntegration_Attribute
    {
        public int ID { get; set; }
        public int EntityId { get; set; }
        public string EntityType { get; set; }
        public int IntegrationinstanceId { get; set; }
        public string AttrType { get; set; }
        public string AttrValue { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual IntegrationInstance IntegrationInstance { get; set; }
    }
}
