//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoalDistribution
    {
        public int Id { get; set; }
        public int MeasureId { get; set; }
        public int DistributionType { get; set; }
        public int DistributionPeriodNumber { get; set; }
        public double DistributionPercentage { get; set; }
        public Nullable<int> Period { get; set; }
    
        public virtual Measure Measure { get; set; }
    }
}
