//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goal
    {
        public Goal()
        {
            this.GoalDimensions = new HashSet<GoalDimension>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Quarter { get; set; }
        public int Year { get; set; }
        public int MeasureId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public Nullable<bool> IsFiscalGoal { get; set; }
    
        public virtual ICollection<GoalDimension> GoalDimensions { get; set; }
        public virtual Measure Measure { get; set; }
    }
}
