//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GraphRelation
    {
        public int Id { get; set; }
        public int ParentGraphId { get; set; }
        public int ChildGraphId { get; set; }
        public string CenterPie { get; set; }
        public Nullable<int> SizePie { get; set; }
        public Nullable<bool> IsYAxisDisplayRight { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    
        public virtual ReportGraph ReportGraph { get; set; }
        public virtual ReportGraph ReportGraph1 { get; set; }
    }
}
