//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomepageContent
    {
        public int Id { get; set; }
        public Nullable<int> DashboardContentId { get; set; }
        public Nullable<int> KeyDataId { get; set; }
        public int DashboardId { get; set; }
        public int RowNumber { get; set; }
        public int DisplayOrder { get; set; }
        public bool DisplayTitle { get; set; }
        public int Height { get; set; }
        public int Width { get; set; }
        public bool DisplayDateStamp { get; set; }
        public Nullable<int> HomepageID { get; set; }
    
        public virtual Dashboard Dashboard { get; set; }
        public virtual Homepage Homepage { get; set; }
        public virtual KeyData KeyData { get; set; }
    }
}
