//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Homepage
    {
        public Homepage()
        {
            this.HomepageContents = new HashSet<HomepageContent>();
            this.HomepageDimensions = new HashSet<HomepageDimension>();
            this.MenuItems = new HashSet<MenuItem>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public int DisplayOrder { get; set; }
        public string CustomCSS { get; set; }
        public Nullable<int> Rows { get; set; }
        public Nullable<int> Columns { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsComparisonDisplay { get; set; }
        public Nullable<int> HelpTextId { get; set; }
    
        public virtual HelpText HelpText { get; set; }
        public virtual ICollection<HomepageContent> HomepageContents { get; set; }
        public virtual ICollection<HomepageDimension> HomepageDimensions { get; set; }
        public virtual ICollection<MenuItem> MenuItems { get; set; }
    }
}
