//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegrationInstanceExternalServer
    {
        public int IntegrationInstanceExternalServerId { get; set; }
        public int IntegrationInstanceId { get; set; }
        public string SFTPServerName { get; set; }
        public string SFTPFileLocation { get; set; }
        public string SFTPUserName { get; set; }
        public string SFTPPassword { get; set; }
        public string SFTPPort { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int CreatedBy { get; set; }
        public int ModifiedBy { get; set; }
    
        public virtual IntegrationInstance IntegrationInstance { get; set; }
    }
}
