//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegrationWorkFrontTacticApprovalOption
    {
        public IntegrationWorkFrontTacticApprovalOption()
        {
            this.IntegrationWorkFrontTacticSettings = new HashSet<IntegrationWorkFrontTacticSetting>();
        }
    
        public int Id { get; set; }
        public string ApprovalOption { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<IntegrationWorkFrontTacticSetting> IntegrationWorkFrontTacticSettings { get; set; }
    }
}
