//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegrationWorkFrontUser
    {
        public int Id { get; set; }
        public string WorkFrontUserId { get; set; }
        public string WorkFrontUserName { get; set; }
        public int IntegrationInstanceId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual IntegrationInstance IntegrationInstance { get; set; }
    }
}
