//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegrationInstanceLog
    {
        public IntegrationInstanceLog()
        {
            this.IntegrationInstanceSections = new HashSet<IntegrationInstanceSection>();
        }
    
        public int IntegrationInstanceLogId { get; set; }
        public int IntegrationInstanceId { get; set; }
        public System.DateTime SyncStart { get; set; }
        public Nullable<System.DateTime> SyncEnd { get; set; }
        public string Status { get; set; }
        public string ErrorDescription { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsAutoSync { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual IntegrationInstance IntegrationInstance { get; set; }
        public virtual ICollection<IntegrationInstanceSection> IntegrationInstanceSections { get; set; }
    }
}
