//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegrationWorkFrontRequest
    {
        public int Id { get; set; }
        public int PlanTacticId { get; set; }
        public int IntegrationInstanceId { get; set; }
        public string RequestId { get; set; }
        public string RequestName { get; set; }
        public int QueueId { get; set; }
        public int WorkFrontUserId { get; set; }
        public string WorkFrontRequestStatus { get; set; }
        public string ResolvingObjType { get; set; }
        public string ResolvingObjId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual IntegrationInstance IntegrationInstance { get; set; }
        public virtual IntegrationWorkFrontRequestQueue IntegrationWorkFrontRequestQueue { get; set; }
        public virtual IntegrationWorkFrontUser IntegrationWorkFrontUser { get; set; }
        public virtual Plan_Campaign_Program_Tactic Plan_Campaign_Program_Tactic { get; set; }
    }
}
