//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegrationWorkFrontProgram_Mapping
    {
        public int ID { get; set; }
        public int PortfolioTableId { get; set; }
        public string ProgramId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual IntegrationWorkFrontPortfolio IntegrationWorkFrontPortfolio { get; set; }
    }
}
