//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegrationWorkFrontRequestQueue
    {
        public IntegrationWorkFrontRequestQueue()
        {
            this.IntegrationWorkFrontRequests = new HashSet<IntegrationWorkFrontRequest>();
        }
    
        public int Id { get; set; }
        public string RequestQueueId { get; set; }
        public string RequestQueueName { get; set; }
        public bool IsDeleted { get; set; }
        public int IntegrationInstanceId { get; set; }
    
        public virtual IntegrationInstance IntegrationInstance { get; set; }
        public virtual ICollection<IntegrationWorkFrontRequest> IntegrationWorkFrontRequests { get; set; }
    }
}
