//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegrationWorkFrontPortfolio
    {
        public IntegrationWorkFrontPortfolio()
        {
            this.IntegrationWorkFrontPortolio_Mapping = new HashSet<IntegrationWorkFrontPortolio_Mapping>();
        }
    
        public int Id { get; set; }
        public int IntegrationInstanceId { get; set; }
        public string PortfolioId { get; set; }
        public string PortfolioName { get; set; }
        public int PlanProgramId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<IntegrationWorkFrontPortolio_Mapping> IntegrationWorkFrontPortolio_Mapping { get; set; }
    }
}
