//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegrationInstancePlanEntityLog
    {
        public int IntegrationInstanceId { get; set; }
        public int EntityId { get; set; }
        public string EntityType { get; set; }
        public System.DateTime SyncTimeStamp { get; set; }
        public string Operation { get; set; }
        public string Status { get; set; }
        public string ErrorDescription { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<int> IntegrationInstanceSectionId { get; set; }
        public long IntegrationInstancePlanLogEntityId { get; set; }
    
        public virtual IntegrationInstance IntegrationInstance { get; set; }
        public virtual IntegrationInstanceSection IntegrationInstanceSection { get; set; }
    }
}
