//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegrationWorkFrontPortfolio
    {
        public IntegrationWorkFrontPortfolio()
        {
            this.IntegrationWorkFrontPortfolio_Mapping = new HashSet<IntegrationWorkFrontPortfolio_Mapping>();
            this.IntegrationWorkFrontProgram_Mapping = new HashSet<IntegrationWorkFrontProgram_Mapping>();
        }
    
        public int Id { get; set; }
        public int IntegrationInstanceId { get; set; }
        public string PortfolioId { get; set; }
        public string PortfolioName { get; set; }
        public Nullable<int> PlanProgramId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> PlanId { get; set; }
    
        public virtual ICollection<IntegrationWorkFrontPortfolio_Mapping> IntegrationWorkFrontPortfolio_Mapping { get; set; }
        public virtual ICollection<IntegrationWorkFrontProgram_Mapping> IntegrationWorkFrontProgram_Mapping { get; set; }
    }
}
