//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegrationWorkFrontTemplate
    {
        public IntegrationWorkFrontTemplate()
        {
            this.TacticTypes = new HashSet<TacticType>();
        }
    
        public int ID { get; set; }
        public int IntegrationInstanceId { get; set; }
        public string TemplateId { get; set; }
        public string Template_Name { get; set; }
        public int IsDeleted { get; set; }
    
        public virtual IntegrationInstance IntegrationInstance { get; set; }
        public virtual ICollection<TacticType> TacticTypes { get; set; }
    }
}
