//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegrationInstanceSection
    {
        public IntegrationInstanceSection()
        {
            this.IntegrationInstancePlanEntityLogs = new HashSet<IntegrationInstancePlanEntityLog>();
        }
    
        public int IntegrationInstanceSectionId { get; set; }
        public int IntegrationInstanceLogId { get; set; }
        public int IntegrationInstanceId { get; set; }
        public string SectionName { get; set; }
        public System.DateTime SyncStart { get; set; }
        public Nullable<System.DateTime> SyncEnd { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreateBy { get; set; }
    
        public virtual IntegrationInstance IntegrationInstance { get; set; }
        public virtual IntegrationInstanceLog IntegrationInstanceLog { get; set; }
        public virtual ICollection<IntegrationInstancePlanEntityLog> IntegrationInstancePlanEntityLogs { get; set; }
    }
}
