//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineItem_Budget
    {
        public int Id { get; set; }
        public int BudgetDetailId { get; set; }
        public int PlanLineItemId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<byte> Weightage { get; set; }
    
        public virtual Budget_Detail Budget_Detail { get; set; }
        public virtual Plan_Campaign_Program_Tactic_LineItem Plan_Campaign_Program_Tactic_LineItem { get; set; }
    }
}
