//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model_Audience_Inbound
    {
        public int ModelAudienceInboundId { get; set; }
        public int ModelId { get; set; }
        public string Quarter { get; set; }
        public Nullable<int> Impressions { get; set; }
        public Nullable<double> ClickThroughRate { get; set; }
        public Nullable<int> Visits { get; set; }
        public Nullable<double> RegistrationRate { get; set; }
        public Nullable<int> PPC_ClickThroughs { get; set; }
        public Nullable<double> PPC_CostperClickThrough { get; set; }
        public Nullable<double> PPC_RegistrationRate { get; set; }
        public Nullable<int> GC_GuaranteedCPLBudget { get; set; }
        public Nullable<double> GC_CostperLead { get; set; }
        public Nullable<int> CSC_NonGuaranteedCPLBudget { get; set; }
        public Nullable<double> CSC_CostperLead { get; set; }
        public Nullable<int> TDM_DigitalMediaBudget { get; set; }
        public Nullable<double> TDM_CostperLead { get; set; }
        public Nullable<int> TP_PrintMediaBudget { get; set; }
        public Nullable<double> TP_CostperLead { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    
        public virtual Model Model { get; set; }
    }
}
