//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelReview
    {
        public int ModelReviewId { get; set; }
        public int ModelFunnelId { get; set; }
        public int FunnelFieldId { get; set; }
        public Nullable<double> MarketingSourced { get; set; }
        public Nullable<double> MarketingDays { get; set; }
        public Nullable<double> ProspectingSourced { get; set; }
        public Nullable<double> ProspectingDays { get; set; }
        public Nullable<double> SalesSourced { get; set; }
        public Nullable<double> SalesDays { get; set; }
        public Nullable<double> BlendedTotal { get; set; }
        public Nullable<double> BlendedDays { get; set; }
        public bool IsBaseline { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    
        public virtual Funnel_Field Funnel_Field { get; set; }
        public virtual Model_Funnel Model_Funnel { get; set; }
    }
}
