//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public Notification()
        {
            this.User_Notification = new HashSet<User_Notification>();
        }
    
        public int NotificationId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string NotificationType { get; set; }
        public string EmailContent { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string NotificationInternalUseOnly { get; set; }
        public string Subject { get; set; }
        public int CreatedBy { get; set; }
        public int ModifiedBy { get; set; }
    
        public virtual ICollection<User_Notification> User_Notification { get; set; }
    }
}
