//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan_Team
    {
        public int PlanId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int TeamMemberId { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual Plan Plan { get; set; }
    }
}
