//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan_Improvement_Campaign
    {
        public Plan_Improvement_Campaign()
        {
            this.Plan_Improvement_Campaign_Program = new HashSet<Plan_Improvement_Campaign_Program>();
        }
    
        public int ImprovementPlanCampaignId { get; set; }
        public int ImprovePlanId { get; set; }
        public string Title { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsDeployedToIntegration { get; set; }
        public string IntegrationInstanceCampaignId { get; set; }
        public Nullable<System.DateTime> LastSyncDate { get; set; }
        public string Description { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual Plan Plan { get; set; }
        public virtual ICollection<Plan_Improvement_Campaign_Program> Plan_Improvement_Campaign_Program { get; set; }
    }
}
