//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportTable
    {
        public ReportTable()
        {
            this.ReportTableColumns = new HashSet<ReportTableColumn>();
            this.ReportTableDimensions = new HashSet<ReportTableDimension>();
            this.ReportTableRowExcludes = new HashSet<ReportTableRowExclude>();
        }
    
        public int id { get; set; }
        public string TableName { get; set; }
        public Nullable<int> DashboardId { get; set; }
        public Nullable<bool> ShowFooterRow { get; set; }
        public Nullable<bool> IsLastDateOnly { get; set; }
        public Nullable<int> DefaultRows { get; set; }
        public Nullable<int> SortColumnNumber { get; set; }
        public string SortDirection { get; set; }
        public bool IsGoalDisplay { get; set; }
        public bool IsGoalDisplayForFilterCritaria { get; set; }
        public int DateRangeGoalOption { get; set; }
        public bool IsComparisonDisplay { get; set; }
        public string CustomQuery { get; set; }
        public string ComparisonType { get; set; }
        public bool IsGoalDisplayAsColumn { get; set; }
        public string CustomFilter { get; set; }
        public Nullable<bool> IsICustomFilterApply { get; set; }
        public Nullable<int> TotalDecimalPlaces { get; set; }
        public string MagnitudeValue { get; set; }
    
        public virtual Dashboard Dashboard { get; set; }
        public virtual ICollection<ReportTableColumn> ReportTableColumns { get; set; }
        public virtual ICollection<ReportTableDimension> ReportTableDimensions { get; set; }
        public virtual ICollection<ReportTableRowExclude> ReportTableRowExcludes { get; set; }
    }
}
