//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportGraph
    {
        public ReportGraph()
        {
            this.GraphRelations = new HashSet<GraphRelation>();
            this.GraphRelations1 = new HashSet<GraphRelation>();
        }
    
        public int id { get; set; }
        public string GraphType { get; set; }
        public Nullable<bool> IsLableDisplay { get; set; }
        public string LabelPosition { get; set; }
        public Nullable<bool> IsLegendVisible { get; set; }
        public string LegendPosition { get; set; }
        public Nullable<bool> IsDataLabelVisible { get; set; }
        public string DataLablePosition { get; set; }
        public Nullable<int> DefaultRows { get; set; }
        public string ChartAttribute { get; set; }
        public Nullable<double> ConfidenceLevel { get; set; }
        public bool IsGoalDisplay { get; set; }
        public bool IsGoalDisplayForFilterCritaria { get; set; }
        public int DateRangeGoalOption { get; set; }
        public Nullable<bool> IsComparisonDisplay { get; set; }
        public string CustomQuery { get; set; }
        public Nullable<bool> IsIndicatorDisplay { get; set; }
        public bool IsSortByValue { get; set; }
        public string SortOrder { get; set; }
        public Nullable<bool> DisplayGoalAsLine { get; set; }
        public string CustomFilter { get; set; }
        public string DrillDownCustomQuery { get; set; }
        public string DrillDownXFilter { get; set; }
        public Nullable<int> TotalDecimalPlaces { get; set; }
        public string MagnitudeValue { get; set; }
        public Nullable<bool> IsICustomFilterApply { get; set; }
        public Nullable<bool> IsTrendLineDisplay { get; set; }
    
        public virtual ICollection<GraphRelation> GraphRelations { get; set; }
        public virtual ICollection<GraphRelation> GraphRelations1 { get; set; }
    }
}
