//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportTableColumn
    {
        public int id { get; set; }
        public int ReportTableId { get; set; }
        public int MeasureId { get; set; }
        public int ColumnOrder { get; set; }
        public string SymbolType { get; set; }
        public Nullable<int> DimensionId { get; set; }
        public string ComparisonType { get; set; }
        public string MagnitudeValue { get; set; }
        public Nullable<int> TotalDecimalPlaces { get; set; }
    
        public virtual Dimension Dimension { get; set; }
        public virtual ReportTable ReportTable { get; set; }
        public virtual Measure Measure { get; set; }
    }
}
