//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportAxi
    {
        public int id { get; set; }
        public int ReportGraphId { get; set; }
        public string AxisName { get; set; }
        public int Dimensionid { get; set; }
        public string GroupDimensionValue { get; set; }
    
        public virtual Dimension Dimension { get; set; }
    }
}
