//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportGraphColumn
    {
        public int id { get; set; }
        public int ReportGraphId { get; set; }
        public int MeasureId { get; set; }
        public Nullable<int> ColumnOrder { get; set; }
        public string SymbolType { get; set; }
        public Nullable<bool> DisplayInTable { get; set; }
        public Nullable<bool> PrevMeasureCalculation { get; set; }
        public Nullable<bool> DisplayAsNumerator { get; set; }
        public Nullable<bool> DisplayAsDenominator { get; set; }
        public Nullable<int> WeekMeasureId { get; set; }
        public Nullable<int> MonthMeasureId { get; set; }
        public Nullable<int> QuarterMeasureId { get; set; }
        public Nullable<int> YearMeasureId { get; set; }
        public Nullable<int> TotalDecimalPlaces { get; set; }
        public string MagnitudeValue { get; set; }
    
        public virtual Measure Measure { get; set; }
        public virtual Measure Measure1 { get; set; }
        public virtual Measure Measure2 { get; set; }
        public virtual Measure Measure3 { get; set; }
        public virtual Measure Measure4 { get; set; }
    }
}
