//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stage
    {
        public Stage()
        {
            this.BestInClasses = new HashSet<BestInClass>();
            this.ImprovementTacticType_Metric = new HashSet<ImprovementTacticType_Metric>();
            this.Model_Stage = new HashSet<Model_Stage>();
            this.Plan_Campaign_Program_Tactic = new HashSet<Plan_Campaign_Program_Tactic>();
            this.TacticTypes = new HashSet<TacticType>();
        }
    
        public int StageId { get; set; }
        public string Title { get; set; }
        public System.Guid ClientId { get; set; }
        public string Description { get; set; }
        public Nullable<int> Level { get; set; }
        public string ColorCode { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public string Code { get; set; }
        public string Funnel { get; set; }
        public string ConversionTitle { get; set; }
    
        public virtual ICollection<BestInClass> BestInClasses { get; set; }
        public virtual ICollection<ImprovementTacticType_Metric> ImprovementTacticType_Metric { get; set; }
        public virtual ICollection<Model_Stage> Model_Stage { get; set; }
        public virtual ICollection<Plan_Campaign_Program_Tactic> Plan_Campaign_Program_Tactic { get; set; }
        public virtual ICollection<TacticType> TacticTypes { get; set; }
    }
}
