//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncFrequency
    {
        public int IntegrationInstanceId { get; set; }
        public string Frequency { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string DayofWeek { get; set; }
        public string Day { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> NextSyncDate { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual IntegrationInstance IntegrationInstance { get; set; }
    }
}
