//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tactic_MediaCodes_CustomFieldMapping
    {
        public int Id { get; set; }
        public int TacticId { get; set; }
        public int MediaCodeId { get; set; }
        public Nullable<int> CustomFieldId { get; set; }
        public string CustomFieldValue { get; set; }
    
        public virtual CustomField CustomField { get; set; }
        public virtual Tactic_MediaCodes Tactic_MediaCodes { get; set; }
    }
}
