//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TacticTypeCost_Base
    {
        public long id { get; set; }
        public Nullable<int> DimensionValue1 { get; set; }
        public Nullable<int> DimensionValue2 { get; set; }
        public Nullable<int> DimensionValue3 { get; set; }
        public Nullable<int> DimensionValue4 { get; set; }
        public Nullable<int> DimensionValue5 { get; set; }
        public Nullable<int> DimensionValue6 { get; set; }
        public Nullable<int> DimensionValue7 { get; set; }
        public Nullable<bool> dirty { get; set; }
    
        public virtual DimensionValue DimensionValue { get; set; }
        public virtual DimensionValue DimensionValue8 { get; set; }
        public virtual DimensionValue DimensionValue9 { get; set; }
        public virtual DimensionValue DimensionValue10 { get; set; }
        public virtual DimensionValue DimensionValue11 { get; set; }
        public virtual DimensionValue DimensionValue12 { get; set; }
        public virtual DimensionValue DimensionValue13 { get; set; }
    }
}
