//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TacticTypeCost_Value0
    {
        public long id { get; set; }
        public long TacticTypeCost { get; set; }
        public Nullable<int> d1d2 { get; set; }
        public Nullable<int> d1d2d3 { get; set; }
        public Nullable<int> d1d2d3d4 { get; set; }
        public Nullable<int> d1d2d3d4d5 { get; set; }
        public Nullable<int> d1d2d3d4d5d6 { get; set; }
        public Nullable<int> d1d2d3d4d5d6d7 { get; set; }
        public Nullable<int> d1d2d3d4d5d7 { get; set; }
        public Nullable<int> d1d2d3d4d6 { get; set; }
        public Nullable<int> d1d2d3d4d6d7 { get; set; }
        public Nullable<int> d1d2d3d4d7 { get; set; }
        public Nullable<int> d1d2d3d5 { get; set; }
        public Nullable<int> d1d2d3d5d6 { get; set; }
        public Nullable<int> d1d2d3d5d6d7 { get; set; }
        public Nullable<int> d1d2d3d5d7 { get; set; }
        public Nullable<int> d1d2d3d6 { get; set; }
        public Nullable<int> d1d2d3d6d7 { get; set; }
        public Nullable<int> d1d2d3d7 { get; set; }
        public Nullable<int> d1d2d4 { get; set; }
        public Nullable<int> d1d2d4d5 { get; set; }
        public Nullable<int> d1d2d4d5d6 { get; set; }
        public Nullable<int> d1d2d4d5d6d7 { get; set; }
        public Nullable<int> d1d2d4d5d7 { get; set; }
        public Nullable<int> d1d2d4d6 { get; set; }
        public Nullable<int> d1d2d4d6d7 { get; set; }
        public Nullable<int> d1d2d4d7 { get; set; }
        public Nullable<int> d1d2d5 { get; set; }
        public Nullable<int> d1d2d5d6 { get; set; }
        public Nullable<int> d1d2d5d6d7 { get; set; }
        public Nullable<int> d1d2d5d7 { get; set; }
        public Nullable<int> d1d2d6 { get; set; }
        public Nullable<int> d1d2d6d7 { get; set; }
        public Nullable<int> d1d2d7 { get; set; }
        public Nullable<int> d1d3 { get; set; }
        public Nullable<int> d1d3d4 { get; set; }
        public Nullable<int> d1d3d4d5 { get; set; }
        public Nullable<int> d1d3d4d5d6 { get; set; }
        public Nullable<int> d1d3d4d5d6d7 { get; set; }
        public Nullable<int> d1d3d4d5d7 { get; set; }
        public Nullable<int> d1d3d4d6 { get; set; }
        public Nullable<int> d1d3d4d6d7 { get; set; }
        public Nullable<int> d1d3d4d7 { get; set; }
        public Nullable<int> d1d3d5 { get; set; }
        public Nullable<int> d1d3d5d6 { get; set; }
        public Nullable<int> d1d3d5d6d7 { get; set; }
        public Nullable<int> d1d3d5d7 { get; set; }
        public Nullable<int> d1d3d6 { get; set; }
        public Nullable<int> d1d3d6d7 { get; set; }
        public Nullable<int> d1d3d7 { get; set; }
        public Nullable<int> d1d4 { get; set; }
        public Nullable<int> d1d4d5 { get; set; }
        public Nullable<int> d1d4d5d6 { get; set; }
        public Nullable<int> d1d4d5d6d7 { get; set; }
        public Nullable<int> d1d4d5d7 { get; set; }
        public Nullable<int> d1d4d6 { get; set; }
        public Nullable<int> d1d4d6d7 { get; set; }
        public Nullable<int> d1d4d7 { get; set; }
        public Nullable<int> d1d5 { get; set; }
        public Nullable<int> d1d5d6 { get; set; }
        public Nullable<int> d1d5d6d7 { get; set; }
        public Nullable<int> d1d5d7 { get; set; }
        public Nullable<int> d1d6 { get; set; }
        public Nullable<int> d1d6d7 { get; set; }
        public Nullable<int> d1d7 { get; set; }
    
        public virtual d1d2 d1d21 { get; set; }
        public virtual d1d2d3 d1d2d31 { get; set; }
        public virtual d1d2d3d4 d1d2d3d41 { get; set; }
        public virtual d1d2d3d4d5 d1d2d3d4d51 { get; set; }
        public virtual d1d2d3d4d5d6 d1d2d3d4d5d61 { get; set; }
        public virtual d1d2d3d4d5d6d7 d1d2d3d4d5d6d71 { get; set; }
        public virtual d1d2d3d4d5d7 d1d2d3d4d5d71 { get; set; }
        public virtual d1d2d3d4d6 d1d2d3d4d61 { get; set; }
        public virtual d1d2d3d4d6d7 d1d2d3d4d6d71 { get; set; }
        public virtual d1d2d3d4d7 d1d2d3d4d71 { get; set; }
        public virtual d1d2d3d5 d1d2d3d51 { get; set; }
        public virtual d1d2d3d5d6 d1d2d3d5d61 { get; set; }
        public virtual d1d2d3d5d6d7 d1d2d3d5d6d71 { get; set; }
        public virtual d1d2d3d5d7 d1d2d3d5d71 { get; set; }
        public virtual d1d2d3d6 d1d2d3d61 { get; set; }
        public virtual d1d2d3d6d7 d1d2d3d6d71 { get; set; }
        public virtual d1d2d3d7 d1d2d3d71 { get; set; }
        public virtual d1d2d4 d1d2d41 { get; set; }
        public virtual d1d2d4d5 d1d2d4d51 { get; set; }
        public virtual d1d2d4d5d6 d1d2d4d5d61 { get; set; }
        public virtual d1d2d4d5d6d7 d1d2d4d5d6d71 { get; set; }
        public virtual d1d2d4d5d7 d1d2d4d5d71 { get; set; }
        public virtual d1d2d4d6 d1d2d4d61 { get; set; }
        public virtual d1d2d4d6d7 d1d2d4d6d71 { get; set; }
        public virtual d1d2d4d7 d1d2d4d71 { get; set; }
        public virtual d1d2d5 d1d2d51 { get; set; }
        public virtual d1d2d5d6 d1d2d5d61 { get; set; }
        public virtual d1d2d5d6d7 d1d2d5d6d71 { get; set; }
        public virtual d1d2d5d7 d1d2d5d71 { get; set; }
        public virtual d1d2d6 d1d2d61 { get; set; }
        public virtual d1d2d6d7 d1d2d6d71 { get; set; }
        public virtual d1d2d7 d1d2d71 { get; set; }
        public virtual d1d3 d1d31 { get; set; }
        public virtual d1d3d4 d1d3d41 { get; set; }
        public virtual d1d3d4d5 d1d3d4d51 { get; set; }
        public virtual d1d3d4d5d6 d1d3d4d5d61 { get; set; }
        public virtual d1d3d4d5d6d7 d1d3d4d5d6d71 { get; set; }
        public virtual d1d3d4d5d7 d1d3d4d5d71 { get; set; }
        public virtual d1d3d4d6 d1d3d4d61 { get; set; }
        public virtual d1d3d4d6d7 d1d3d4d6d71 { get; set; }
        public virtual d1d3d4d7 d1d3d4d71 { get; set; }
        public virtual d1d3d5 d1d3d51 { get; set; }
        public virtual d1d3d5d6 d1d3d5d61 { get; set; }
        public virtual d1d3d5d6d7 d1d3d5d6d71 { get; set; }
        public virtual d1d3d5d7 d1d3d5d71 { get; set; }
        public virtual d1d3d6 d1d3d61 { get; set; }
        public virtual d1d3d6d7 d1d3d6d71 { get; set; }
        public virtual d1d3d7 d1d3d71 { get; set; }
        public virtual d1d4 d1d41 { get; set; }
        public virtual d1d4d5 d1d4d51 { get; set; }
        public virtual d1d4d5d6 d1d4d5d61 { get; set; }
        public virtual d1d4d5d6d7 d1d4d5d6d71 { get; set; }
        public virtual d1d4d5d7 d1d4d5d71 { get; set; }
        public virtual d1d4d6 d1d4d61 { get; set; }
        public virtual d1d4d6d7 d1d4d6d71 { get; set; }
        public virtual d1d4d7 d1d4d71 { get; set; }
        public virtual d1d5 d1d51 { get; set; }
        public virtual d1d5d6 d1d5d61 { get; set; }
        public virtual d1d5d6d7 d1d5d6d71 { get; set; }
        public virtual d1d5d7 d1d5d71 { get; set; }
        public virtual d1d6 d1d61 { get; set; }
        public virtual d1d6d7 d1d6d71 { get; set; }
        public virtual d1d7 d1d71 { get; set; }
        public virtual TacticTypeCost TacticTypeCost1 { get; set; }
    }
}
