//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TacticTypeCost_VIEW
    {
        public long Id { get; set; }
        public Nullable<int> TacticTypeId { get; set; }
        public string TacticType { get; set; }
        public Nullable<double> MQL { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<double> CW { get; set; }
        public Nullable<double> Cost_MQL { get; set; }
        public Nullable<double> Cost_CW { get; set; }
        public Nullable<int> PlanId { get; set; }
        public string PlanName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string C123456789_123456789_123456789_123456789_123456789_59 { get; set; }
        public string Area_of_Interest_363 { get; set; }
        public string Audience_Segment_141 { get; set; }
        public string Audience_Segment_55 { get; set; }
        public string Audience_133 { get; set; }
        public string Audience_138 { get; set; }
        public string Audience_63 { get; set; }
        public string Audience_68 { get; set; }
        public string Audience_70 { get; set; }
        public string Audience_72 { get; set; }
        public string Audience_76 { get; set; }
        public string Business_Unit_103 { get; set; }
        public string Business_Unit_142 { get; set; }
        public string Business_Unit_155 { get; set; }
        public string Business_Unit_18 { get; set; }
        public string Business_Unit_85 { get; set; }
        public string Business_Unit_90 { get; set; }
        public string Business_Unit_95 { get; set; }
        public string Business_Unit_97 { get; set; }
        public string Business_Unit_99 { get; set; }
        public string Buyer_Type_154 { get; set; }
        public string Buyer_s_Journey_15 { get; set; }
        public string Buyers_Journey_328 { get; set; }
        public string Buyers_Journey_4 { get; set; }
        public string Campaign_Goal_364 { get; set; }
        public string Campaign_Record_Type_21 { get; set; }
        public string Campaign_Record_Type_370 { get; set; }
        public string Campaign_Segment_14 { get; set; }
        public string Campaign_Status_20 { get; set; }
        public string Company_Size_356 { get; set; }
        public string Country_11 { get; set; }
        public string Country_143 { get; set; }
        public string Enable_Bizable_Touchpoints_369 { get; set; }
        public string Geography_112 { get; set; }
        public string Geography_117 { get; set; }
        public string Geography_122 { get; set; }
        public string Geography_124 { get; set; }
        public string Geography_126 { get; set; }
        public string Geography_130 { get; set; }
        public string Geography_144 { get; set; }
        public string Industry___Legal_Only_327 { get; set; }
        public string Industry_153 { get; set; }
        public string Marketing_Campaign_Owner__371 { get; set; }
        public string Pan_Segment_330 { get; set; }
        public string Personas_329 { get; set; }
        public string Product_10 { get; set; }
        public string Product_146 { get; set; }
        public string Program_Type_147 { get; set; }
        public string Program_Type_8 { get; set; }
        public string Program_Type_9 { get; set; }
        public string Segment_326 { get; set; }
        public string Sub_Region_336 { get; set; }
        public string Tele_Route_148 { get; set; }
        public string Theater_108 { get; set; }
        public string Theatre_Region_367 { get; set; }
        public string Theatre_365 { get; set; }
        public string Vendor_13 { get; set; }
        public string Vertical_Segment_132 { get; set; }
        public string Vertical_Segment_150 { get; set; }
        public string Vertical_149 { get; set; }
        public string Vertical_29 { get; set; }
        public string Vertical_33 { get; set; }
        public string Vertical_354 { get; set; }
        public string Vertical_37 { get; set; }
        public string Vertical_42 { get; set; }
        public string Vertical_44 { get; set; }
        public string Vertical_46 { get; set; }
        public string Vertical_50 { get; set; }
        public string Verticals___Investigative_only_331 { get; set; }
        public Nullable<int> d1d2 { get; set; }
        public Nullable<int> d1d2d3 { get; set; }
        public Nullable<int> d1d2d3d4 { get; set; }
        public Nullable<int> d1d2d3d4d5 { get; set; }
        public Nullable<int> d1d2d3d4d5d6 { get; set; }
        public Nullable<int> d1d2d3d4d5d6d7 { get; set; }
        public Nullable<int> d1d2d3d4d5d7 { get; set; }
        public Nullable<int> d1d2d3d4d6 { get; set; }
        public Nullable<int> d1d2d3d4d6d7 { get; set; }
        public Nullable<int> d1d2d3d4d7 { get; set; }
        public Nullable<int> d1d2d3d5 { get; set; }
        public Nullable<int> d1d2d3d5d6 { get; set; }
        public Nullable<int> d1d2d3d5d6d7 { get; set; }
        public Nullable<int> d1d2d3d5d7 { get; set; }
        public Nullable<int> d1d2d3d6 { get; set; }
        public Nullable<int> d1d2d3d6d7 { get; set; }
        public Nullable<int> d1d2d3d7 { get; set; }
        public Nullable<int> d1d2d4 { get; set; }
        public Nullable<int> d1d2d4d5 { get; set; }
        public Nullable<int> d1d2d4d5d6 { get; set; }
        public Nullable<int> d1d2d4d5d6d7 { get; set; }
        public Nullable<int> d1d2d4d5d7 { get; set; }
        public Nullable<int> d1d2d4d6 { get; set; }
        public Nullable<int> d1d2d4d6d7 { get; set; }
        public Nullable<int> d1d2d4d7 { get; set; }
        public Nullable<int> d1d2d5 { get; set; }
        public Nullable<int> d1d2d5d6 { get; set; }
        public Nullable<int> d1d2d5d6d7 { get; set; }
        public Nullable<int> d1d2d5d7 { get; set; }
        public Nullable<int> d1d2d6 { get; set; }
        public Nullable<int> d1d2d6d7 { get; set; }
        public Nullable<int> d1d2d7 { get; set; }
        public Nullable<int> d1d3 { get; set; }
        public Nullable<int> d1d3d4 { get; set; }
        public Nullable<int> d1d3d4d5 { get; set; }
        public Nullable<int> d1d3d4d5d6 { get; set; }
        public Nullable<int> d1d3d4d5d6d7 { get; set; }
        public Nullable<int> d1d3d4d5d7 { get; set; }
        public Nullable<int> d1d3d4d6 { get; set; }
        public Nullable<int> d1d3d4d6d7 { get; set; }
        public Nullable<int> d1d3d4d7 { get; set; }
        public Nullable<int> d1d3d5 { get; set; }
        public Nullable<int> d1d3d5d6 { get; set; }
        public Nullable<int> d1d3d5d6d7 { get; set; }
        public Nullable<int> d1d3d5d7 { get; set; }
        public Nullable<int> d1d3d6 { get; set; }
        public Nullable<int> d1d3d6d7 { get; set; }
        public Nullable<int> d1d3d7 { get; set; }
        public Nullable<int> d1d4 { get; set; }
        public Nullable<int> d1d4d5 { get; set; }
        public Nullable<int> d1d4d5d6 { get; set; }
        public Nullable<int> d1d4d5d6d7 { get; set; }
        public Nullable<int> d1d4d5d7 { get; set; }
        public Nullable<int> d1d4d6 { get; set; }
        public Nullable<int> d1d4d6d7 { get; set; }
        public Nullable<int> d1d4d7 { get; set; }
        public Nullable<int> d1d5 { get; set; }
        public Nullable<int> d1d5d6 { get; set; }
        public Nullable<int> d1d5d6d7 { get; set; }
        public Nullable<int> d1d5d7 { get; set; }
        public Nullable<int> d1d6 { get; set; }
        public Nullable<int> d1d6d7 { get; set; }
        public Nullable<int> d1d7 { get; set; }
        public Nullable<int> DimensionValue1 { get; set; }
        public Nullable<int> DimensionValue2 { get; set; }
        public Nullable<int> DimensionValue3 { get; set; }
        public Nullable<int> DimensionValue4 { get; set; }
        public Nullable<int> DimensionValue5 { get; set; }
        public Nullable<int> DimensionValue6 { get; set; }
        public Nullable<int> DimensionValue7 { get; set; }
    }
}
