//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionLineItemMapping
    {
        public int TransactionLineItemMappingId { get; set; }
        public int TransactionId { get; set; }
        public int LineItemId { get; set; }
        public Nullable<double> Amount { get; set; }
        public System.DateTime DateModified { get; set; }
        public int ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateProcessed { get; set; }
    
        public virtual Plan_Campaign_Program_Tactic_LineItem Plan_Campaign_Program_Tactic_LineItem { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
