//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Notification_Messages
    {
        public int NotificationId { get; set; }
        public string ComponentName { get; set; }
        public Nullable<int> ComponentId { get; set; }
        public Nullable<int> EntityId { get; set; }
        public string Description { get; set; }
        public string ActionName { get; set; }
        public bool IsRead { get; set; }
        public Nullable<System.DateTime> ReadDate { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public System.Guid RecipientId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> ClientID { get; set; }
    }
}
