//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_CoulmnView
    {
        public User_CoulmnView()
        {
            this.User_CoulmnView_attribute = new HashSet<User_CoulmnView_attribute>();
        }
    
        public int ViewId { get; set; }
        public string ViewName { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<bool> IsDefault { get; set; }
    
        public virtual ICollection<User_CoulmnView_attribute> User_CoulmnView_attribute { get; set; }
    }
}
