//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Permission
    {
        public int Id { get; set; }
        public Nullable<int> DashboardId { get; set; }
        public Nullable<int> ApplicationActivityId { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public string PermissionType { get; set; }
        public Nullable<int> HomePageId { get; set; }
    }
}
