//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_CoulmnView_attribute
    {
        public int Id { get; set; }
        public int ViewId { get; set; }
        public string AttributeType { get; set; }
        public string AttributeId { get; set; }
        public Nullable<int> ColumnOrder { get; set; }
    
        public virtual User_CoulmnView User_CoulmnView { get; set; }
    }
}
