//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClientWise_EntityList
    {
        public int EntityId { get; set; }
        public string EntityTitle { get; set; }
        public int ClientId { get; set; }
        public string Entity { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int EntityOrder { get; set; }
        public string PlanTitle { get; set; }
        public int PlanId { get; set; }
    }
}
