//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenuePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Versioning
    {
        public int Id { get; set; }
        public string Release_Name { get; set; }
        public System.DateTime Date_Applied { get; set; }
        public string Version { get; set; }
    }
}
